# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/TEST/TEST.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST || ORIG_REF_NAME==TEST} -quiet] -quiet

# IP: bd/TEST/ip/TEST_test_0_0/TEST_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_test_0_0 || ORIG_REF_NAME==TEST_test_0_0} -quiet] -quiet

# IP: bd/TEST/ip/TEST_clk_wiz_0_0/TEST_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TEST_clk_wiz_0_0 || ORIG_REF_NAME==TEST_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/TEST/TEST_ooc.xdc
