##IO、LED、SW
set_property PACKAGE_PIN N14 [get_ports io0_0]
set_property IOSTANDARD LVCMOS33 [get_ports io0_0]
set_property PACKAGE_PIN M14 [get_ports io1_0]
set_property IOSTANDARD LVCMOS33 [get_ports io1_0]
set_property PACKAGE_PIN C4 [get_ports io2_0]
set_property IOSTANDARD LVCMOS33 [get_ports io2_0]
set_property PACKAGE_PIN B13 [get_ports io3_0]
set_property IOSTANDARD LVCMOS33 [get_ports io3_0]
set_property PACKAGE_PIN N10 [get_ports io4_0]
set_property IOSTANDARD LVCMOS33 [get_ports io4_0]
set_property PACKAGE_PIN M10 [get_ports io5_0]
set_property IOSTANDARD LVCMOS33 [get_ports io5_0]
set_property PACKAGE_PIN B14 [get_ports io6_0]
set_property IOSTANDARD LVCMOS33 [get_ports io6_0]
set_property PACKAGE_PIN D3 [get_ports io7_0]
set_property IOSTANDARD LVCMOS33 [get_ports io7_0]
set_property PACKAGE_PIN P5 [get_ports io8_0]
set_property IOSTANDARD LVCMOS33 [get_ports io8_0]
set_property PACKAGE_PIN M3 [get_ports io9_0]
set_property IOSTANDARD LVCMOS33 [get_ports io9_0]
set_property PACKAGE_PIN C3 [get_ports io10_0]
set_property IOSTANDARD LVCMOS33 [get_ports io10_0]
set_property PACKAGE_PIN M4 [get_ports io11_0]
set_property IOSTANDARD LVCMOS33 [get_ports io11_0]
set_property PACKAGE_PIN C10 [get_ports io12_0]
set_property IOSTANDARD LVCMOS33 [get_ports io12_0]
set_property PACKAGE_PIN D10 [get_ports io13_0]
set_property IOSTANDARD LVCMOS33 [get_ports io13_0]
set_property PACKAGE_PIN M2 [get_ports k1_0]
set_property IOSTANDARD LVCMOS33 [get_ports k1_0]
set_property PACKAGE_PIN L2 [get_ports k2_0]
set_property IOSTANDARD LVCMOS33 [get_ports k2_0]
set_property PACKAGE_PIN L3 [get_ports k3_0]
set_property IOSTANDARD LVCMOS33 [get_ports k3_0]
set_property PACKAGE_PIN K3 [get_ports k4_0]
set_property IOSTANDARD LVCMOS33 [get_ports k4_0]
set_property PACKAGE_PIN J1 [get_ports led1_0]
set_property IOSTANDARD LVCMOS33 [get_ports led1_0]
set_property PACKAGE_PIN A13 [get_ports led2_0]
set_property IOSTANDARD LVCMOS33 [get_ports led2_0]
##三色灯
## Clock signal 100 MHz
set_property -dict { PACKAGE_PIN H4  IOSTANDARD LVCMOS33 } [get_ports { clk_in1_0 }]; #IO_L13P_T2_MRCC_35 Sch=sysclk
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { clk_in1_0 }];
set_property -dict { PACKAGE_PIN N11  IOSTANDARD LVCMOS33 } [get_ports { fpga_rgb_0 }]; #IO_L13P_T2_MRCC_35 Sch=sysclk
#######ADC
set_property PACKAGE_PIN J4 [get_ports adc_en_0]
set_property PACKAGE_PIN J3 [get_ports adc_date_0[0]]
set_property PACKAGE_PIN J2 [get_ports adc_date_0[1]]
set_property PACKAGE_PIN D12 [get_ports adc_date_0[2]]
set_property PACKAGE_PIN E12 [get_ports adc_date_0[3]]
set_property PACKAGE_PIN F12 [get_ports adc_date_0[4]]
set_property PACKAGE_PIN C11 [get_ports adc_date_0[5]]
set_property PACKAGE_PIN H11 [get_ports adc_date_0[6]]
set_property PACKAGE_PIN H12 [get_ports adc_date_0[7]]
set_property PACKAGE_PIN C5 [get_ports clk_out2_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out2_0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_en_0]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[0]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[1]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[2]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[3]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[4]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[5]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[6]]
set_property IOSTANDARD LVCMOS33 [get_ports adc_date_0[7]]
####################DAC
set_property PACKAGE_PIN L1 [get_ports din_0]
set_property PACKAGE_PIN M1 [get_ports clk_out3_0]
set_property PACKAGE_PIN N1 [get_ports sync_0]
set_property IOSTANDARD LVCMOS33 [get_ports din_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_out3_0]
set_property IOSTANDARD LVCMOS33 [get_ports sync_0]
######################模拟开关
set_property PACKAGE_PIN H3 [get_ports IN1_0]
set_property IOSTANDARD LVCMOS33 [get_ports IN1_0]
set_property PACKAGE_PIN E11 [get_ports IN4_0]
set_property IOSTANDARD LVCMOS33 [get_ports IN4_0]
set_property PACKAGE_PIN P12 [get_ports SCL_0]
set_property IOSTANDARD LVCMOS33 [get_ports SCL_0]
set_property PACKAGE_PIN P13 [get_ports SDA_0]
set_property IOSTANDARD LVCMOS33 [get_ports SDA_0]