webtalk_init -webtalk_dir C:\\Users\\Opex9020\\Desktop\\SEA-Tutorial\\Experiment-of-SEA\\FPGA-Demo-Project\\Gyro-Demo\\Gyro_Demo_Microblaze\\Gyro_Demo\\Gyro_Demo.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-11-12 19:41:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fqjpamri9pr4127a2lrfv6gjjb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.527 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1573558069077" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key Arch -value "spartan7" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key Device -value "7s15" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1573558069077"
webtalk_add_data -client sdk -key uid -value "1573558099374" -context "sdk\\\\bsp/1573558099374"
webtalk_add_data -client sdk -key hwid -value "1573558069077" -context "sdk\\\\bsp/1573558099374"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1573558099374"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\bsp/1573558099374"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1573558099374"
webtalk_add_data -client sdk -key uid -value "1573558110150" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key hwid -value "1573558069077" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key bspid -value "1573558099374" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key projSize -value "103.578125" -context "sdk\\\\application/1573558110150"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1573558863293"
webtalk_transmit -clientid 410638993 -regid "" -xml C:\\Users\\Opex9020\\Desktop\\SEA-Tutorial\\Experiment-of-SEA\\FPGA-Demo-Project\\Gyro-Demo\\Gyro_Demo_Microblaze\\Gyro_Demo\\Gyro_Demo.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Opex9020\\Desktop\\SEA-Tutorial\\Experiment-of-SEA\\FPGA-Demo-Project\\Gyro-Demo\\Gyro_Demo_Microblaze\\Gyro_Demo\\Gyro_Demo.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Opex9020\\Desktop\\SEA-Tutorial\\Experiment-of-SEA\\FPGA-Demo-Project\\Gyro-Demo\\Gyro_Demo_Microblaze\\Gyro_Demo\\Gyro_Demo.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
